#!/bin/bash

# Pod will stay up for 5 minutes
RETRIES=150
CREDS="/var/tmp/bind-creds"

for r in $(seq 1 $RETRIES); do
    if [ -f $CREDS ]; then
        echo "Waiting for broker to gather the bind credentials..."
        sleep 2
    else
        echo "Broker has received bind credentials."
        echo "Waiting for broker exec to complete..."
        sleep 5
        exit 0
    fi
done

echo "bind-init timed out after ${RETRIES} retries."
exit 1
