FROM centos:7
MAINTAINER Ansible Playbook Bundle Community

LABEL "com.redhat.apb.version"="0.1.0"

RUN mkdir -p /usr/share/ansible/openshift \
             /etc/ansible /opt/apb /opt/ansible

RUN yum -y install epel-release centos-release-openshift-origin \
    && yum -y update \
    && yum -y install bind-utils \
                      gcc \
                      libffi-devel \
                      make \
                      net-tools \
                      openssl-devel \
                      origin \
                      origin-clients \
                      python-cffi \
                      python-devel \
                      python-pip \
                      python-setuptools \
    && yum clean all

RUN git clone https://github.com:/ansible/ansible.git
RUN cd ansible \
    && pip install -U setuptools \
    && git checkout devel \
    && python setup.py install

RUN git clone https://github.com/openshift/openshift-restclient-python
RUN cd openshift-restclient-python \
    && pip install -r requirements.txt \
    && python setup.py install

RUN echo "localhost ansible_connection=local" > /etc/ansible/hosts \
    && echo '[defaults]' > /etc/ansible/ansible.cfg \
    && echo 'roles_path = /opt/ansible/roles' >> /etc/ansible/ansible.cfg \
    && echo 'library = /usr/share/ansible/openshift' >> /etc/ansible/ansible.cfg

COPY files/etc/ansible/* /etc/ansible/
COPY files/usr/bin/* /usr/bin/

RUN useradd -u 1001 -r -g 0 -M -b /opt/apb -s /sbin/nologin -c "apb user" apb
RUN chown -R apb: /opt/{ansible,apb}

ENTRYPOINT ["entrypoint.sh"]
