FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"aWQ6IDU1YzUzYTVkLTY1YTYtNGMyNy04OGZjLWUwMjc0MTBiMTg4MgpuYW1lOiBoZWxsby13b3Js\
ZC1hcGIKaW1hZ2U6IGFuc2libGVwbGF5Ym9va2J1bmRsZS9oZWxsby13b3JsZC1hcGIKZGVzY3Jp\
cHRpb246IGhlbGxvLXdvcmxkLWFwYiBkZXNjcmlwdGlvbgpiaW5kYWJsZTogRmFsc2UKYXN5bmM6\
IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiAKICBsb25nRGVzY3JpcHRpb246IAog\
IGltYWdlVXJsOiAKICBkb2N1bWVudGF0aW9uVXJsOiAKICBkZXBlbmRlbmNpZXM6CiAgICAtIGRv\
Y2tlci5pby9hbnNpYmxlcGxheWJvb2tidW5kbGUvaGVsbG8td29ybGQ6bGF0ZXN0CiAgICAKcGFy\
YW1ldGVyczogW10KICAKcmVxdWlyZWQ6IFtdCiAg"


ADD playbooks /opt/apb/actions
ADD roles /opt/ansible/roles

USER apb