FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"bmFtZTogdGhlbG91bmdlLWFwYgppbWFnZTogYW5zaWJsZXBsYXlib29rYnVuZGxlL3RoZWxvdW5n\
ZS1hcGIKZGVzY3JpcHRpb246IFRoaXMgaXMgYSBzYW1wbGUgYXBwbGljYXRpb24gZ2VuZXJhdGVk\
IGJ5IGFwYiBpbml0CmJpbmRhYmxlOiBGYWxzZQphc3luYzogb3B0aW9uYWwKbWV0YWRhdGE6CiAg\
ZGlzcGxheU5hbWU6IFRoZSBMb3VuZ2UgKEFQQikKICBpbWFnZVVybDogaHR0cHM6Ly9hc3NldHMt\
Y2RuLmdpdGh1Yi5jb20vaW1hZ2VzL2ljb25zL2Vtb2ppL3VuaWNvZGUvMWY0YWMucG5nCnBsYW5z\
OgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVzY3JpcHRpb246IFRoaXMgZGVmYXVsdCBwbGFuIGRl\
cGxveXMgdGhlbG91bmdlLWFwYgogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBw\
YXJhbWV0ZXJzOiBbXQo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
