- name: create namespace
  openshift_v1_project:
    name: '{{ namespace }}'

- name: create volumes
  k8s_v1_persistent_volume_claim:
    name: demodb
    namespace: '{{ namespace }}'
    state: present
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: 1Gi

- name: create service
  k8s_v1_service:
    name: '{{ dbservice_name }}'
    namespace: '{{ namespace }}'
    state: present
    labels:
      app: pyzip-demo-db-apb
      service: '{{ dbservice_name }}'
    selector:
      app: pyzip-demo-db-apb
      service: '{{ dbservice_name }}'
    ports:
    - name: port-5432
      port: 5432
      protocol: TCP
      target_port: 5432

- name: create image stream
  openshift_v1_image_stream:
    name: postgresql
    namespace: '{{ namespace }}'
    tags:
      - name: postgis
    docker_image_repository: docker.io/fabianvf/postgresql

- name: create deployment config
  openshift_v1_deployment_config:
    name: demodb
    namespace: '{{ namespace }}'
    labels:
      app: pyzip-demo-db-apb
      service: '{{ dbservice_name }}'
    replicas: 1
    selector:
      app: pyzip-demo-db-apb
      service: '{{ dbservice_name }}'
    strategy_type: Rolling
    strategy_rolling_params:
      interval_seconds: 1
      max_surge: 25%
      max_unavailable: 25%
      timeout_seconds: 600
      update_period_seconds: 1
    spec_template_metadata_labels:
      app: pyzip-demo-db-apb
      service: '{{ dbservice_name }}'
    containers:
    - env:
      - name: POSTGRES_PASSWORD
        value: '{{ database_password }}'
      - name: POSTGRES_USER
        value: '{{ database_user }}'
      - name: POSTGRES_DB
        value: '{{ database_name }}'
      image: docker.io/fabianvf/postgresql:postgis
      image_pull_policy: IfNotPresent
      name: demodb
      ports:
      - container_port: 5432
        protocol: TCP
      resources: {}
      security_context: {}
      termination_message_path: /dev/termination-log
      volume_mounts:
      - mount_path: /var/lib/pgsql/data
        name: demodb
      working_dir: /
    dns_policy: ClusterFirst
    restart_policy: Always
    termination_grace_period_seconds: 30
    volumes:
    - name: demodb
      persistent_volume_claim:
        claim_name: demodb
    test: false
    triggers:
    - type: ImageChange
      image_change_params:
        automatic: true
        container_names:
        - demodb
        _from:
          kind: ImageStreamTag
          name: postgresql:postgis


- name: Wait for the database to come up
  wait_for:
    port: 5432
    host: "{{ dbservice_name }}"
    timeout: 300

- name: seed database
  shell: "PGPASSWORD={{ database_password }} psql -U {{ database_user }} -d {{ database_name }} -p 5432 -h  {{ dbservice_name }} -f {{ role_path }}/files/{{ item }}"
  with_items:
    - parkcoord.sql
    - airports.ddl
    - zipcodes.ddl
    - airports.sql
    - zipcodes.sql

- name: encode bind credentials
  shell: 'echo "{\"POSTGRES_HOST\": \"{{ dbservice_name }}\", \"POSTGRES_PORT\": \"5432\", \"POSTGRES_USER\": \"{{ database_user }}\", \"POSTGRES_PASSWORD\": \"{{ database_password }}\", \"POSTGRES_DB\": \"{{ database_name }}\"}" | base64 -w 0'
  register: encoded_bind_credentials

- copy:
    content: "{{ encoded_bind_credentials.stdout }}"
    dest: /var/tmp/bind-creds
