- name: unbind rhscl-postgresql-apb to application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: unbind-rhscl-postgresql-apb-openshift
    playbook_debug: true
    when: _apb_provision_creds.USER_CREATION_TYPE == "multiple"
