- name: "set service state to {{ state }}"
  k8s_v1_service:
    name: mongodb
    namespace: "{{ namespace }}"
    labels:
      app: mongodb-apb
      service: mongodb
    selector:
      app: mongodb-apb
      service: mongodb
    ports:
    - name: port-27017
      port: 27017
      protocol: TCP
      target_port: 27017
    state: "{{ state }}"
  register: mongodb_service

- name: scale deployment down
  openshift_v1_deployment_config:
    name: mongodb
    namespace: "{{ namespace }}"
    replicas: 0
    state: present
    selector:
      app: mongodb-apb
      service: mongodb
  when: state == "absent"

- name: delete replication controller
  k8s_v1_replication_controller:
    name: mongodb-1
    namespace: "{{ namespace }}"
    state: absent
  when: state == "absent"

- include: dev.yml
  when: _apb_plan_id == "dev"

- include: prod.yml
  when: _apb_plan_id == "prod"

- name: Wait for mongodb to come up
  wait_for:
    port: 27017
    host: "{{ mongodb_service.service.spec.cluster_ip }}"
    timeout: 300
  when: state == "present"

- name: encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: mongodb
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: "{{ mongodb_user }}"
      DB_PASSWORD: "{{ mongodb_password }}"
      DB_NAME: "{{ mongodb_database }}"
  when: state == "present"
