- name: Deprovision pyzip-demo-db-apb from openshift
  hosts: localhost
  gather_facts: false
  connection: local
  post_tasks:
  - k8s_v1_persistent_volume_claim:
      name: postgresql
      namespace: '{{ namespace }}'
      state: absent
  - openshift_v1_deployment_config:
      name: postgresql
      namespace: '{{ namespace }}'
      replicas: 0
      state: absent
  - k8s_v1_service:
      name: '{{ postgresql_service_name }}'
      namespace: '{{ namespace }}'
      state: absent
  - openshift_v1_image_stream:
      name: postgresql
      namespace: '{{ namespace }}'
      state: absent
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  vars:
    namespace: '{{ namespace }}'
    postgresql_service_name: '{{ postgresql_service_name }}'
