- name: Deploy pyzip-demo-db-apb to openshift
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: provision-pyzip-demo-db-apb
    playbook_debug: false
