- name: Deploy rhscl-postgresql-apb to openshift
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: rhscl-postgresql-apb-openshift
    playbook_debug: false
