FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"bmFtZTogaGFzdGViaW4tYXBiCmltYWdlOiBkeW11cnJheS9oYXN0ZWJpbi1hcGIKZGVzY3JpcHRp\
b246IFRoaXMgaXMgYSBzYW1wbGUgYXBwbGljYXRpb24gZ2VuZXJhdGVkIGJ5IGFwYiBpbml0CmJp\
bmRhYmxlOiBGYWxzZQphc3luYzogb3B0aW9uYWwKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IGhh\
c3RlYmluCnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVzY3JpcHRpb246IFRoaXMgZGVm\
YXVsdCBwbGFuIGRlcGxveXMgaGFzdGViaW4tYXBiCiAgICBmcmVlOiBUcnVlCiAgICBtZXRhZGF0\
YToge30KICAgIHBhcmFtZXRlcnM6CiAgICAgIC0gbmFtZTogaGFzdGViaW5fcG9ydAogICAgICAg\
IHR5cGU6IGludAogICAgICAgIGRlZmF1bHQ6IDc3NzcKICAgICAgICB0aXRsZTogSGFzdGViaW4g\
UG9ydAogICAgICAtIG5hbWU6IG1heF9sZW5ndGgKICAgICAgICB0eXBlOiBpbnQKICAgICAgICBk\
ZWZhdWx0OiA0MDAwMDAKICAgICAgICB0aXRsZTogTWF4IGxlbmd0aCBvZiBoYXN0ZWJpbiBlbnRy\
eQogICAgICAtIG5hbWU6IGtleV9sZW5ndGgKICAgICAgICB0eXBlOiBpbnQKICAgICAgICBkZWZh\
dWx0OiAxMAogICAgICAgIHRpdGxlOiBMZW5ndGggb2YgaGFzdGViaW4ga2V5Cg=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
