FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"bmFtZTogaGFzdGViaW4tYXBiCmltYWdlOiBhbnNpYmxlcGxheWJvb2tidW5kbGUvaGFzdGViaW4t\
YXBiCmRlc2NyaXB0aW9uOiBUaGlzIGlzIGEgc2FtcGxlIGFwcGxpY2F0aW9uIGdlbmVyYXRlZCBi\
eSBhcGIgaW5pdApiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRp\
c3BsYXlOYW1lOiBIYXN0ZWJpbiAoQVBCKQpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRl\
c2NyaXB0aW9uOiBUaGlzIGRlZmF1bHQgcGxhbiBkZXBsb3lzIGhhc3RlYmluLWFwYgogICAgZnJl\
ZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJhbWV0ZXJzOgogICAgICAtIG5hbWU6IGhh\
c3RlYmluX3BvcnQKICAgICAgICB0eXBlOiBpbnQKICAgICAgICBkZWZhdWx0OiA3Nzc3CiAgICAg\
ICAgdGl0bGU6IEhhc3RlYmluIFBvcnQKICAgICAgLSBuYW1lOiBtYXhfbGVuZ3RoCiAgICAgICAg\
dHlwZTogaW50CiAgICAgICAgZGVmYXVsdDogNDAwMDAwCiAgICAgICAgdGl0bGU6IE1heCBsZW5n\
dGggb2YgaGFzdGViaW4gZW50cnkKICAgICAgLSBuYW1lOiBrZXlfbGVuZ3RoCiAgICAgICAgdHlw\
ZTogaW50CiAgICAgICAgZGVmYXVsdDogMTAKICAgICAgICB0aXRsZTogTGVuZ3RoIG9mIGhhc3Rl\
YmluIGtleQo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
