FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"aWQ6IDQzZjBiZjBiLTQzOGMtNDk1Yy04MTI3LTExYjEyNDZkZGVhNApuYW1lOiBweXppcC1kZW1v\
LWFwYgppbWFnZTogYW5zaWJsZXBsYXlib29rYnVuZGxlL3B5emlwLWRlbW8tYXBiCmRlc2NyaXB0\
aW9uOiBQeXRob24gWmlwIERlbW8gQVBCIEltcGxlbWVudGF0aW9uCmJpbmRhYmxlOiBGYWxzZQph\
c3luYzogb3B0aW9uYWwKbWV0YWRhdGE6CiAgZGlzcGxheU5hbWU6IFB5emlwIERlbW8gKEFQQikK\
ICBsb25nRGVzY3JpcHRpb246IEFQQiBJbXBsZW1lbnRhdGlvbiBvZiB0aGUgUHl0aG9uIHdlYmFw\
cCwgaHR0cHM6Ly9naXRodWIuY29tL2Z1c29yL3B5LXppcC1kZW1vCiAgaW1hZ2VVcmw6IAogIGRv\
Y3VtZW50YXRpb25Vcmw6IGh0dHBzOi8vZ2l0aHViLmNvbS9mdXNvci9hcGItZXhhbXBsZXMvdHJl\
ZS9tYXN0ZXIvcHl6aXAtZGVtby1hcGIKICBkZXBlbmRlbmNpZXM6CiAgICAtIGRvY2tlci5pby9h\
bnNpYmxlcGxheWJvb2tidW5kbGUvcHktemlwLWRlbW86bGF0ZXN0CiAgICAKcGFyYW1ldGVyczog\
W10KICAKcmVxdWlyZWQ6IFtdCiAg"

ADD playbooks /opt/apb/actions
ADD roles /opt/ansible/roles

USER apb
