FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"aWQ6IDQzZjBiZjBiLTQzOGMtNDk1Yy04MTI3LTExYjEyNDZkZGVhNApuYW1lOiBweXppcC1kZW1v\
LWFwYgppbWFnZTogYW5zaWJsZXBsYXlib29rYnVuZGxlL3B5emlwLWRlbW8tYXBiCmRlc2NyaXB0\
aW9uOiBQeXRob24gWmlwIERlbW8gQVBCIEltcGxlbWVudGF0aW9uCmJpbmRhYmxlOiBGYWxzZQph\
c3luYzogb3B0aW9uYWwKbWV0YWRhdGE6IAogIGRvY3VtZW50YXRpb25Vcmw6IGh0dHBzOi8vZ2l0\
aHViLmNvbS9mdXNvci9hcGItZXhhbXBsZXMvdHJlZS9tYXN0ZXIvcHl6aXAtZGVtby1hcGIKICBk\
ZXBlbmRlbmNpZXM6IFsnZG9ja2VyLmlvL2Fuc2libGVwbGF5Ym9va2J1bmRsZS9weS16aXAtZGVt\
bzpsYXRlc3QnXQogIGRpc3BsYXlOYW1lOiBQeXppcCBEZW1vIChBUEIpCiAgbG9uZ0Rlc2NyaXB0\
aW9uOiBBUEIgSW1wbGVtZW50YXRpb24gb2YgdGhlIFB5dGhvbiB3ZWJhcHAsIGh0dHBzOi8vZ2l0\
aHViLmNvbS9mdXNvci9weS16aXAtZGVtbwogIApwYXJhbWV0ZXJzOiBbXQogIApyZXF1aXJlZDog\
W10KICA="

ADD playbooks /opt/apb/actions
ADD roles /opt/ansible/roles

USER apb
