FROM ansibleplaybookbundle/apb-base
MAINTAINER Ansible Playbook Bundle Community

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"aWQ6IDliNzBlNmJmLTI2ZjgtNGMxZi1hNTdmLTA3NTAxMzg4YzFlOApuYW1lOiBhbnNpYmxlYXBw\
L3dvcmRwcmVzcy1oYS1hbnNpYmxlYXBwCmRlc2NyaXB0aW9uOiBoaWdoIGF2YWlsYWJpbGl0eSB3\
b3JkcHJlc3MgZGVwbG95bWVudApiaW5kYWJsZTogdHJ1ZQphc3luYzogIm9wdGlvbmFsIgpwYXJh\
bWV0ZXJzOgogIC0gbmFtZTogcHJvamVjdF9uYW1lCiAgICBkZXNjcmlwdGlvbjogTmFtZXNwYWNl\
IHRvIGRlcGxveSBjb250YWluZXJzIHRvCiAgICBkZWZhdWx0OiB3b3JkcHJlc3MtaGEK"
COPY roles /opt/ansible/roles
COPY playbooks /opt/apb/actions

USER apb
